using System;
using System.Collections.Generic;
using System.IO;
using VacationApp.DailyLog;
using VacationApp.Trips;

namespace VacationApp.UI
{
    public class DailyLogUI
    {
        private readonly DailyLogManager dailyLogManager;
        private readonly TripManager tripManager;
        
        public DailyLogUI(DailyLogManager dailyLogManager, TripManager tripManager)
        {
            this.dailyLogManager = dailyLogManager;
            this.tripManager = tripManager;
        }
        
        // show the daily log main menu
        public void ShowDailyLogMenu(int tripId, string tripName)
        {
            while (true)
            {
                Console.Clear();
                DrawHeader($"Daily Log: {tripName}");
                
                var trip = tripManager.GetTrip(tripId);
                
                Console.WriteLine($"Trip Dates: {trip.StartDate:MMM d} - {trip.EndDate:MMM d, yyyy}");
                Console.WriteLine();
                
                // get current date (default to today or trip end date if trip is in the past)
                DateTime selectedDate = DateTime.Today;
                if (selectedDate > trip.EndDate)
                    selectedDate = trip.EndDate;
                if (selectedDate < trip.StartDate)
                    selectedDate = trip.StartDate;
                
                DisplayDailyLog(tripId, selectedDate);
                
                string[] options = {
                    "Previous Day",
                    "Next Day",
                    "Select Date",
                    "Edit Daily Log",
                    "Export Daily Log",
                    "Back to Main Menu"
                };
                
                Console.WriteLine("\nUse ↑/↓ arrow keys to navigate, ENTER to select:");
                Console.WriteLine();
                
                int selectedOption = ShowMenu(options);
                
                switch (selectedOption)
                {
                    case 0: // previous day
                        selectedDate = selectedDate.AddDays(-1);
                        if (selectedDate < trip.StartDate)
                            selectedDate = trip.StartDate;
                        break;
                    case 1: // next day
                        selectedDate = selectedDate.AddDays(1);
                        if (selectedDate > trip.EndDate)
                            selectedDate = trip.EndDate;
                        break;
                    case 2: // select date
                        selectedDate = SelectDate(trip.StartDate, trip.EndDate);
                        break;
                    case 3: // edit daily log
                        EditDailyLog(tripId, selectedDate);
                        break;
                    case 4: // export daily log
                        ExportDailyLog(tripId, selectedDate);
                        break;
                    case 5: // back to main menu
                        return;
                }
            }
        }
        
        // display a daily log
        private void DisplayDailyLog(int tripId, DateTime date)
        {
            var log = dailyLogManager.GetDailyLog(tripId, date);
            
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine($"Date: {date:MMMM d, yyyy}");
            Console.ResetColor();
            
            if (log.IsAutoGenerated)
            {
                Console.WriteLine("(Auto-generated log)");
            }
            
            Console.WriteLine();
            Console.WriteLine(log.Summary);
        }
        
        // select a date
        private DateTime SelectDate(DateTime startDate, DateTime endDate)
        {
            Console.Clear();
            DrawHeader("Select Date");
            
            Console.WriteLine($"Trip dates: {startDate:MMM d, yyyy} - {endDate:MMM d, yyyy}");
            Console.WriteLine("\nEnter date [YYYY-MM-DD]:");
            
            DateTime selectedDate;
            while (true)
            {
                string input = Console.ReadLine();
                
                if (DateTime.TryParse(input, out selectedDate))
                {
                    selectedDate = selectedDate.Date; // remove time component
                    
                    if (selectedDate < startDate)
                    {
                        Console.ForegroundColor = ConsoleColor.Yellow;
                        Console.WriteLine($"Date is before trip start. Using trip start date: {startDate:yyyy-MM-dd}");
                        Console.ResetColor();
                        selectedDate = startDate;
                        break;
                    }
                    else if (selectedDate > endDate)
                    {
                        Console.ForegroundColor = ConsoleColor.Yellow;
                        Console.WriteLine($"Date is after trip end. Using trip end date: {endDate:yyyy-MM-dd}");
                        Console.ResetColor();
                        selectedDate = endDate;
                        break;
                    }
                    else
                    {
                        break;
                    }
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Invalid date format. Please use YYYY-MM-DD.");
                    Console.ResetColor();
                    Console.Write("Enter date: ");
                }
            }
            
            return selectedDate;
        }
        
        // edit a daily log
        private void EditDailyLog(int tripId, DateTime date)
        {
            var log = dailyLogManager.GetDailyLog(tripId, date);
            
            Console.Clear();
            DrawHeader($"Edit Daily Log: {date:MMMM d, yyyy}");
            
            Console.WriteLine("Current log content:");
            Console.WriteLine(log.Summary);
            
            Console.WriteLine("\nEnter new content (or press ENTER to keep current):");
            Console.WriteLine("Type END on a separate line when finished.");
            
            string content = "";
            string line;
            while (true)
            {
                line = Console.ReadLine();
                if (line == "END") break;
                content += line + Environment.NewLine;
            }
            
            if (!string.IsNullOrWhiteSpace(content))
            {
                dailyLogManager.UpdateDailyLog(log.Id, content.Trim());
                
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("\nDaily log updated successfully!");
                Console.ResetColor();
            }
            else
            {
                Console.WriteLine("\nNo changes made.");
            }
            
            Console.WriteLine("\nPress any key to return...");
            Console.ReadKey();
        }
        
        //export a daily log
        private void ExportDailyLog(int tripId, DateTime date)
        {
            Console.Clear();
            DrawHeader("Export Daily Log");
            
            Console.WriteLine($"Date: {date:MMMM d, yyyy}");
            
            string[] options = {
                "Plain Text (.txt)",
                "CSV (.csv)",
                "Back"
            };
            
            Console.WriteLine("\nExport format:");
            Console.WriteLine();
            
            int selectedOption = ShowMenu(options);
            
            if (selectedOption == 2) // Back
            {
                return;
            }
            
            string format = selectedOption == 0 ? "Text" : "CSV";
            string extension = selectedOption == 0 ? "txt" : "csv";
            
            // generate a default file name
            string defaultFileName = $"vacation_log_{date:yyyyMMdd}.{extension}";
            
            Console.Write($"\nFile path to save [default: {defaultFileName}]: ");
            string filePath = Console.ReadLine();
            
            if (string.IsNullOrWhiteSpace(filePath))
            {
                filePath = defaultFileName;
            }
            
            try
            {
                string content = dailyLogManager.ExportDailyLog(tripId, date, format);
                File.WriteAllText(filePath, content);
                
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("\nExport complete! File saved to: " + filePath);
                Console.ResetColor();
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("\nError exporting file: " + ex.Message);
                Console.ResetColor();
            }
            
            Console.WriteLine("\nPress any key to return...");
            Console.ReadKey();
        }
        
        // method to draw a header
        private void DrawHeader(string title)
        {
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine(title);
            Console.WriteLine(new string('-', title.Length));
            Console.ResetColor();
        }
        
        // method to show a menu with arrow key navigation
        private int ShowMenu(string[] options)
        {
            int selectedIndex = 0;
            ConsoleKey key;
            int startRow = Console.CursorTop;
            
            do
            {
                // display all menu options
                for (int i = 0; i < options.Length; i++)
                {
                    Console.SetCursorPosition(0, startRow + i);
                    Console.Write(new string(' ', Console.WindowWidth - 1));
                    Console.SetCursorPosition(0, startRow + i);
                    
                    if (i == selectedIndex)
                    {
                        Console.BackgroundColor = ConsoleColor.Gray;
                        Console.ForegroundColor = ConsoleColor.Black;
                        Console.WriteLine($" {options[i]} ");
                        Console.ResetColor();
                    }
                    else
                    {
                        Console.WriteLine($" {options[i]} ");
                    }
                }
                
                // get user selection/key press
                key = Console.ReadKey(true).Key;
                
                // handle arrow keys
                if (key == ConsoleKey.UpArrow)
                {
                    selectedIndex = (selectedIndex > 0) ? selectedIndex - 1 : options.Length - 1;
                }
                else if (key == ConsoleKey.DownArrow)
                {
                    selectedIndex = (selectedIndex < options.Length - 1) ? selectedIndex + 1 : 0;
                }
                
            } while (key != ConsoleKey.Enter);
            
            // move cursor to end of menu
            Console.SetCursorPosition(0, startRow + options.Length);
            
            return selectedIndex;
        }
    }
}